### PR TITLE
:art: #126 - refactor: title bug fixed and heading sizes/weight accor…

### LINKED ISSUE #126: Wrong label on "select all" checkbox
Example: The select all checkbox should either say "Select all 14265 items" or "Select all 143 pages"

wrongpagen

### PR DESCRIPTION
**Pull request by Xaohs**
…ding to design

closes #126

### CODE REVIEW

File: src/components/data/attributelist/attributelist.tsx [hunk 1]
```diff
@@ -43,23 +43,33 @@ export const AttributeList = <T extends object = object>({
...
-    <dl className="mykn-attributelist__list">
-      {fields.map((f) => (
-        <AttributePair<T> key={f.toString()} object={object} field={f} />
-      ))}
-    </dl>
-  </div>
-);
+  return (
+    <>
+      {isTitleAbove && renderTitle}
```
Comment (svenvandescheur) [inline src/components/data/attributelist/attributelist.tsx:52]: This renders the title outside the componet block, which seems weired. Can't we solve this differently, with grid and grid areas for instance?

File: src/design-tokens/compiled/properties.css [hunk 2]
```diff
@@ -40,10 +40,11 @@
   --typography-font-family-body: Lato, sans-serif;
   --typography-font-size-h1: 32px;
   --typography-font-size-h2: 20px;
-  --typography-font-size-h3: 14px;
+  --typography-font-size-h3: 16px;
```
Comment (svenvandescheur) [inline src/design-tokens/compiled/properties.css:43]: did you double check these values with @ZoeReijinga ?

**Review by svenvandescheur — CHANGES_REQUESTED** [review]
